# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
