# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_zone_zone_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='votes',
        ),
    ]
