# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160210_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='zones',
            field=models.ManyToManyField(related_name='services', to='app.Zone'),
        ),
    ]
